---
# defaults file for app

app_github_tag: master
app_deploy_path: /usr/share/nginx/html
app_file_owner: nginx
app_group_owner: adm
app_web_root: public
app_env: 'production'
app_document_root: ''
app_force_new_env: false
app_php_path: /usr/bin/php
app_https: false

app_env_params:
  - regex: '^(APP_NAME=).*$'
    line: '\1{{ app_github_repo }}'
  - regex: '^(APP_URL=).*$'
    line: '\1{{ "https" if app_https else "http" }}://{{ app_github_repo }}'
  - regex: '^(APP_DEBUG=).*$'
    line: '\1{{ "false" if app_env == "production" else "true" }}'
  - regex: '^(DB_DATABASE=)homestead$'
    line: '\1{{ mysql_databases[0].name }}'
  - regex: '^(DB_USERNAME=)homestead$'
    line: '\1{{ mysql_users[0].name }}'
  - regex: '^DB_PASSWORD=secret$'
    line: 'DB_PASSWORD={{ lookup("password", playbook_dir + "/credentials/" + ansible_hostname + "-mysql-user.password chars=ascii_letters,digits,hexdigits,punctuation") }}'
