---
# tasks file for app

- name: Calculate the installation root path for {{ app_github_repo }}
  set_fact:
    installation_root: "{{ app_deploy_path }}/{{ app_github_repo }}-{{ app_github_tag }}"
  tags: app

- name: Calculate {{ app_github_repo }} document root path
  set_fact:
    document_root: "{{ installation_root }}/{{ app_document_root }}"
  tags: app

- name: Calculate {{ app_github_repo }} web root path
  set_fact:
    web_root: "{{ document_root }}/{{ app_web_root }}"
  tags: app

- name: Extract {{ app_github_repo }} package
  unarchive:
    src: https://github.com/{{ app_github_user }}/{{ app_github_repo }}/archive/{{ app_github_tag }}.zip
    dest: "{{ app_deploy_path }}"
    owner: "{{ app_file_owner }}"
    group: "{{ app_group_owner }}"
    remote_src: True
    creates: "{{ installation_root }}"
  notify: restart nginx
  tags: app

- name: Run composer for {{ app_github_repo }}
  composer:
    command: install
    working_dir: "{{ document_root }}"
  when: is_laravel
  tags: app

- name: Create {{ app_github_repo }} Laravel environment configurations
  template:
    src: laravel.env.j2
    dest: "{{ document_root }}/.env"
    owner: "{{ app_file_owner }}"
    group: "{{ app_group_owner }}"
  when: is_laravel
  tags: app
