---
# tasks file for bbqlaser.com

- name: Extract application
  unarchive:
    src: https://github.com/jonathonball/{{ item.domain }}/archive/{{ item.branch }}.zip
    dest: /usr/share/nginx/html
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ php_fpm_pool_group }}"
    remote_src: True
    creates: /usr/share/nginx/html/{{ item.domain }}-{{ item.branch }}
  with_items: "{{ site_data }}"
  notify: restart nginx
  tags: web-application

- name: Ensure socket is owned by "{{ php_fpm_pool_user }}"
  file:
    path: "{{ php_fpm_listen }}"
    state: file
    mode: 0660
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ php_fpm_pool_group }}"
  notify: restart php-fpm
  tags: web-application

- name: Run composer for sites that need it
  composer:
    command: install
    working_dir: "{{ item.root }}/.."
  with_items: "{{ nginx_vhosts }}"
  when: item.run_composer == true
  tags: web-application

- name: Allow port 80 in firewalld
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
  register: firewalld_http
  tags: web-application

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  when: firewalld_http.changed
  tags: web-application
